spring:
  application:
    name: kafka-log-pipeline

  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_log_pipeline
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: log-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.zs.kafka_log_pipeline.*"
    streams:
      application-id: kafka-log-pipeline
      bootstrap-servers: localhost:9092
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

server:
  port: 8080

app:
  kafka:
    topics:
      raw-logs: raw-logs
      error-logs: error-logs
      info-logs: info-logs
      alerts: alerts
    alert:
      error-threshold: 3
      window-size-seconds: 60